name: API_Tests
on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
        
    - name: Setup .NET Core 3.1	
      uses: actions/setup-dotnet@v1	
      with:	
        dotnet-version: 5.0.x
        
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build
      
    - name: Test with the dotnet CLI
      run: dotnet test

