name: Tests
on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

env:
  BuildConfig: Release
  SolutionFile: MySolution.sln

jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 3.1.301
        
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      
      - uses: Amaksik/FoodyAPIv@v0.3 # https://github.com/AArnott/nbgv
        id: Amaksik

      - name: Versioning
        run: echo ${{ steps.nbgv.outputs.SemVer2 }}

      - name: Build with dotnet
        run: dotnet build
              --configuration ${{ env.BuildConfig }}
              /p:Version=${{ steps.nbgv.outputs.AssemblyVersion }}

      - name: Test with dotnet
        run: dotnet test ${{ env.SolutionFile }}
